#Configuration example

logger:
    level: INFO
    name: mm_bot_logger

strategy:
    name: market_maker
    instrument_name: 'BTC-PERP'

    tick_size: 0.5

    depth: 20
    quantity: 0.3
    cancel_orders_on_start: False
    stop_strategy_on_error: True
    cancel_orders_on_reconnection: False

adapter:
    api_key: ''
    api_secret: ''
    streaming:
        symbol: BTC-PERP
        url: wss://api.testnet.emx.com
    execution:
        symbol: BTC-PERP
        url: http://api.testnet.emx.com

