#Configuration example

logger:
    level: INFO
    name: mm_bot_logger

strategy:
    name: market_maker
    instrument_name: 'TEST-PERP'

    tick_size: 0.5

    stop_strategy_on_error: True
    cancel_orders_on_reconnection: False

adapter:
    api_key: ''
    api_secret: ''
    streaming:
        url: wss://api.alpha.emx.com
    execution:
        url: http://api.alpha.emx.com

