logger:
    level: INFO
    name: mm_bot_logger_ethbtc

strategy:
    name: market_maker
    instrument_name: 'ETH-BTC'

    mid_price_based_calculation: False
    tick_size: 0.000001
    price_rounding: 6

    positional_retreat:
        position_increment: null
        retreat_ticks: null

    orders:
        asks: [
                [1, 0.01],
                [2, 0.02],
                [5, 0.03],
              ]
        bids: [
                [1, 0.01],
                [2, 0.02],
                [5, 0.03],
              ]

    stop_strategy_on_error: False

adapter:
    api_key: ''
    api_secret: ''
    streaming:
        symbol: ETH-BTC
        url: wss://api.testnet.emx.com
    execution:
        symbol: ETH-BTC
        url: http://api.testnet.emx.com

