#Configuration example

logger:
    name: prod_strl_eth-btc_h
    level: INFO

strategy:
    name: maker

adapter:
    api_key:
    api_secret:
    streaming:
        url: wss://api.alpha.emx.com
    execution:
        url: http://api.alpha.emx.com

