logger:
    level: INFO
    name: mm_bot_logger_btc-perp
    _path_to_file: /path/to/your/file.txt

strategy:
    name: market_maker
    instrument_name: 'BTC-PERP'

    send_post_only_orders: True
    mid_price_based_calculation: False
    tick_size: 0.5

    positional_retreat:
        position_increment: 0.03
        retreat_ticks: 5

    orders:
        asks: [
                [1, 0.01],
                [3, 0.02],
                [5, 0.03],
              ]
        bids: [
                [1, 0.01],
                [3, 0.02],
                [5, 0.03],
              ]

    stop_strategy_on_error: False

adapter:
    api_key: '03b2014f-e416-47cd-be4c-728cbc336a6e'
    api_secret: 'L4CkbCiduoi5kKtB391RokuNH76BLGvFatCZQYkC3s6PWYEsm1Bj/50UKhb878sehrVfHTJ6OSlfov0iVG1yQw=='
    streaming:
        symbol: BTC-PERP
        url: wss://api.testnet.emx.com
    execution:
        symbol: BTC-PERP
        url: http://api.testnet.emx.com