logger:
    level: INFO
    name: mm_bot_logger_ethbtc

strategy:
    name: market_maker
    instrument_name: 'ETH-BTC'

    send_post_only_orders: True
    mid_price_based_calculation: False
    tick_size: 0.000001

    positional_retreat:
        position_increment: null
        retreat_ticks: null

    orders:
        asks: [
                [1, 0.01],
                [2, 0.02],
                [5, 0.03],
              ]
        bids: [
                [1, 0.01],
                [2, 0.02],
                [5, 0.03],
              ]

    stop_strategy_on_error: False

adapter:
    api_key: '03b2014f-e416-47cd-be4c-728cbc336a6e'
    api_secret: 'L4CkbCiduoi5kKtB391RokuNH76BLGvFatCZQYkC3s6PWYEsm1Bj/50UKhb878sehrVfHTJ6OSlfov0iVG1yQw=='
    streaming:
        symbol: ETH-BTC
        url: wss://api.testnet.emx.com
    execution:
        symbol: ETH-BTC
        url: http://api.testnet.emx.com

